### ISSUE TITLE
key pair <pmaddox@amazon.com> being used for launch configuration

### ISSUE THREAD

**Issue by gsingh04** [awslabs/golang-deployment-pipeline#1]
key pair being used in the cloudformation template infrastructure.yml throws error as we don't have the same key in our account. May be can document it, didn't see it highlighted in Readme or I missed it?

**Comment by PaulMaddox** [comment]
Thanks @gsinghlab - that shouldn't have made it through to the release. 
I'll remove the keypair entirely, if people need to add one back in they can.
